<a href="https://colab.research.google.com/github/nishitha92/ai-ml-roadmap/blob/main/code/Numpy_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

we can initialize numpy arrays from nested python lists, and access elements using square brackets.

In [5]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[2])

a[0] = 5
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0], b[1,1])

<class 'numpy.ndarray'>
(3,)
1 3
[5 2 3]
(2, 3)
1 5


NumPy also provides many functions to create arrays.

In [8]:
import numpy as np

a = np.zeros((2, 2))
print(a)

b = np.ones((1, 2))
print(b)

c = np.full((2, 2), 7)
print(c)

d = np.eye(2)
print(d)

e = np.random.random((2, 2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.74082015 0.79722147]
 [0.79929225 0.65515345]]
