<a href="https://colab.research.google.com/github/nishitha92/ai-ml-roadmap/blob/main/code/Numpy_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy**

## **Arrays**

NumPy Arrays are basically python lists with added features. dtype keyword argument takes in a NumPy type and manually casts the array to the specified type.


we can initialize numpy arrays from nested python lists, and access elements using square brackets.

In [ ]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[2])

a[0] = 5
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0], b[1,1])

<class 'numpy.ndarray'>
(3,)
1 3
[5 2 3]
(2, 3)
1 5


NumPy also provides many functions to create arrays.

In [ ]:
import numpy as np

a = np.zeros((2, 2))
print(a)

b = np.ones((1, 2))
print(b)

c = np.full((2, 2), 7)
print(c)

d = np.eye(2)
print(d)

e = np.random.random((2, 2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.74082015 0.79722147]
 [0.79929225 0.65515345]]


When the elements of a NumPy array are mixed types, then the array's type will be upcast to the highest level type.

Example: if the array contains both integer and float then the integers will cast to the floating point equivalents.

## **B. Copying**
Similar to Python lists, when we make a reference to a NumPy array it doesn't create a different array. Therefore, if we change a value using the reference variable, it changes the original array as well. We get around this by using an array's inherent <u>copy</u> function. the function has no required arguments, and it returns the copied array.


In [2]:
import numpy as np

a = np.array([0, 1])
b = np.array([9, 8])
c = a
print('Array a: {}'.format(repr(a)))
c[0] = 5
print('Array a: {}'.format(repr(a)))

d = b.copy()
d[0] = 6
print('Array b: {}'.format(repr(b)))

Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])


## **C. Casting**
Cast NumPy arrays through inherent <u>astype</u> function. The function's required argument is the new type for the array. it returns the array cast to the new type.

```python
arr = np.array([0,1,2])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)
```

## **D. NaN**
A common usage for np.nan is as a filler value for incomplete data. When we don't want a NumPy array to contain a value at a particular index, we can use np.nan to act as a placeholder.

Note that np.nan cannot take on an integer type.

```python
arr = np.array([np.nan, 1, 2])
print(repr(arr))

np.array([np.nan, 1, 2], dtype=np.float32)
np.array([np.nan, 1, 2], dtype=np.int32) # will result in a valueError.
```

## **E.Infinity**
To represent infinity in NumPy, we use the np.inf special value. We can also represent negative infinity with -np.inf.

```python
arr = np.array([np.inf, 5])
print(repr(arr))
```

## **Ranged Data**

This function acts very similar to the range function in Python, and will always return a 1-D array. You can create ranged data arrays using <u>np.arange</u>

```python
arr = np.arange(5)
print(repr(arr))
```

* If only a single number passed as an argument, it will return an array with integers in the range [0,n).
* For two arguments, m and n, np.arange will return an array with all integers in the range[m,n)
* For three arguments, m, n and s, np.arange will return an array with the integers in the range [m,n) using a step size of s.
* Like np.array and np.arange perform upcasting. It also has the dtype keyword argument to manually cast the array.

## **Linspace**
np.linspace() generates an array of evenly spaced numbers over a specified interval. This function takes in a required first two arguments, for the start and end of the range, respectively. The end of the range is inclusive for np.linspace, unless the keyword argument endpoint is set to False.

```python
arr = np.linspace(5, 11, num=4)
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=False)
print(repr(arr))

arr = np.linspace(5, 11, num=4, dtype=np.int32)
print(repr(arr))
```

## **Reshaping Data**
np.reshape, takes in an array and new shapoe as required arguments. The new shape must exactly contain all the elements from the input array.

We are allowed to use the special value of -1 in at most one dimension of the new shape. The dimension with -1 will take on the value necessary to allow the new shape to contain all the elements of the array.